{% set name = "ppft" %}
{% set version = "1.7.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab34436814e2f18238f35688fd869b2641b2d2d8dca22b8d246f6701dfc954c8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python =2.7|>=3.6
    - pip
    - six >=1.7.3
  run:
    - python =2.7|>=3.6
    - six >=1.7.3

test:
  imports:
    - ppft

about:
  home: https://github.com/uqfoundation/ppft
  license: BSD-3-Clause
  license_file: COPYING
  summary: distributed and parallel python

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
