{% set name = "ppft" %}
{% set version = "1.6.4.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e1aa0d74f832f0528234890165f3e64d34b3103ec1db7c93c9e7f2ad8cc18d2

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - six >=1.7.3
  run:
    - python
    - six >=1.7.3

test:
  imports:
    - ppft

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD-3-Clause
  license_file: COPYING
  summary: distributed and parallel python 

extra:
  recipe-maintainers:
    - jschueller
