{% set name = "ppft" %}
{% set version = "1.7.6.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 73161c67474ea9d81d04bcdad166d399cff3f084d5d2dc21ebdd46c075bbc265

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - ppft
  commands:
    - pip check

about:
  home: https://github.com/uqfoundation/ppft
  license: BSD-3-Clause
  license_file: COPYING
  summary: distributed and parallel python

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
