{% set name = "ppft" %}
{% set version = "1.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f696d4f397ae9b0af39b1faffb31957c51dfbc5a3815856472d4f4e872937ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - ppft
  commands:
    - pip check

about:
  home: https://github.com/uqfoundation/ppft
  license: BSD-3-Clause
  license_file: COPYING
  summary: distributed and parallel python

extra:
  recipe-maintainers:
    - jschueller
    - synapticarbors
