{% set name = "ppft" %}
{% set version = "1.6.4.7.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  md5: 2b196a03bfbc102773f849c6b21e617b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six >=1.7.3
  run:
    - python
    - six >=1.7.3

test:
  imports:
    - ppft

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD 3-Clause
  license_file: COPYING
  summary: distributed and parallel python 

extra:
  recipe-maintainers:
    - jschueller
